parameters:
    pim_datagrid.controller.datagrid.class:       Pim\Bundle\DataGridBundle\Controller\DatagridController
    pim_datagrid.controller.product_export.class: Pim\Bundle\DataGridBundle\Controller\ProductExportController
    pim_datagrid.controller.datagrid_view.class:  Pim\Bundle\DataGridBundle\Controller\DatagridViewController
    pim_datagrid.controller.mass_action.class:    Pim\Bundle\DataGridBundle\Controller\MassActionController

services:
    pim_datagrid.controller.datagrid:
        scope: request
        class: %pim_datagrid.controller.datagrid.class%
        arguments:
            - '@templating'

    pim_datagrid.controller.product_export:
        class: %pim_datagrid.controller.product_export.class%
        scope: request
        arguments:
            - '@request'
            - '@pim_datagrid.adapter.oro_to_pim_grid_filter'
            - '@pim_enrich.factory.mass_edit.job_configuration'
            - '@pim_enrich.saver.mass_edit.configuration'
            - '@pim_import_export.repository.job_instance'

    pim_datagrid.controller.datagrid_view:
        scope: request
        class: %pim_datagrid.controller.datagrid_view.class%
        parent: pim_enrich.controller.abstract_doctrine
        arguments:
            - '@pim_datagrid.manager.datagrid_view'

    pim_datagrid.controller.mass_action:
        scope: request
        class: %pim_datagrid.controller.mass_action.class%
        arguments:
            - '@request'
            - '@pim_datagrid.extension.mass_action.dispatcher'
