connector:
    name: Akeneo Mass Edit Connector
    jobs:
        update_product_value:
            title: update_product_value
            type:  mass_edit
            steps:
                perform:
                    title: update_product_value
                    services:
                        reader:    pim_enrich.mass_edit.filtered.reader
                        processor: pim_enrich.mass_edit.update_product_value.processor
                        writer:    pim_base_connector.writer.doctrine.product
        add_product_value:
            title: add_product_value
            type:  mass_edit
            steps:
                perform:
                    title: add_product_value
                    services:
                        reader:    pim_enrich.mass_edit.filtered.reader
                        processor: pim_enrich.mass_edit.add_product_value.processor
                        writer:    pim_base_connector.writer.doctrine.product
        edit_common_attributes:
            title: edit_common_attributes
            type:  mass_edit
            steps:
                perform:
                    title: edit_common_attributes
                    services:
                        reader:    pim_enrich.mass_edit.filtered.reader
                        processor: pim_enrich.mass_edit.edit_common_attributes.processor
                        writer:    pim_base_connector.writer.doctrine.product
                clean:
                    title: edit_common_attributes_clean
                    class: "%pim_enrich.step.mass_edit.remove_temporary_media.class%"
                    services:
                        cleaner: pim_enrich.mass_edit.temporary_file.cleaner
        csv_product_quick_export:
            title: csv_product_quick_export
            type: quick_export
            steps:
                perform:
                    title: csv_product_quick_export
                    services:
                        reader: pim_enrich.mass_edit.filtered.reader
                        processor: pim_base_connector.processor.csv_serializer.product
                        writer: pim_base_connector.writer.file.csv_product
