parameters:
    pim_enrich.mass_edit.reader.class: Pim\Bundle\EnrichBundle\Reader\MassEdit\FilteredProductReader
    pim_enrich.mass_edit.family.reader.class: Pim\Bundle\EnrichBundle\Reader\MassEdit\FilteredFamilyReader

services:
    pim_enrich.mass_edit.filtered.reader:
        class: %pim_enrich.mass_edit.reader.class%
        arguments:
            - '@pim_catalog.query.product_query_builder_factory'
            - '@doctrine.orm.default_entity_manager'
            - '@akeneo_batch.job_repository'
            - '@pim_enrich.repository.mass_edit'
    pim_enrich.mass_edit.family.reader:
        class: %pim_enrich.mass_edit.family.reader.class%
        arguments:
            - '@pim_enrich.repository.mass_edit'
            - '@pim_catalog.repository.family'
            - '@pim_catalog.factory.product_cursor'
